server:
  port: 8011
spring:
  datasource:
    name: dm8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: dm.jdbc.driver.DmDriver
      url: jdbc:dm://127.0.0.1:5236/SCJGJ_NDWC?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: SCJGJ_NDWC
      password: password
      validationQuery: SELECT 1
      testWhileIdle: true
  redis:
    database: 5
    host: 172.31.129.103
    port: 6379
# 生成token的相关配置
jwt:
  #请求头
  header: Authorization
  #盐值
  base64Secret: scjgjndwcxt
  #过期时间 10秒
  tokenValidityInSeconds: 10000
mybatis-plus:
  configuration:
    #控制台打印日记
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
# 分页配置
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




