server:
  port: 8011
spring:
  datasource:
    name: dm8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: dm.jdbc.driver.DmDriver
      url: jdbc:dm://127.0.0.1:5236/SCJGJ_NDWC?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: SCJGJ_NDWC
      password: password
      validationQuery: SELECT 1
      testWhileIdle: true
  redis:
    database: 8
    host: 172.31.129.103
    port: 6379
# 生成token的相关配置
jwt:
  #请求头
  header: Authorization
  #盐值
  base64Secret: scjgjndwcxt
  #过期时间 分钟
  tokenValidityInSeconds: 30
mybatis-plus:
  configuration:
    #控制台打印日记
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
# 分页配置
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  config: classpath:logback-boot.xml
# 自定义配置
config:
  cas:
    #CAS服务标识
    service: http://10.201.62.2:6889/cas/login?service=http%3A%2F%2F10.194.144.132%3A8082%2FyjxtServer%2Fcas%2Flogin
    #请求验证地址
    url: http://127.0.0.1:8002/yjxtServer
    casUrl: http://127.0.0.1:8002/yjxtServer
    #验证通过跳转页面（跳转到首页或者中转页面）
    loginIp: 127.0.0.1
    loginSuccess: http://${cas.loginIp}:5500/yjxt_web/pages/main.html
    #验证失败跳转页面(回到门户登录页面)
    loginError: http://${cas.loginIp}:5500/yjxt_web/pages/login.html
    appId: demo
    appKey: 123456789
    urlHead: /sjj-tacs
    homePage: www.baidu.com




