CREATE TABLE "SCJGJ_NDWC"."T_GAS_STATION"
(
"ID" INT IDENTITY(4, 1) NOT NULL,
"CODE" VARCHAR(255) DEFAULT '0',
"DISTRICT_CODE" VARCHAR(255),
"DISTRICT_NAME" VARCHAR(255),
"MANAGEMENT_NATURE" VARCHAR(255),
"MANAGEMENT_STATE" VARCHAR(2),
"BRAND" VARCHAR(255),
"NAME" VARCHAR(255),
"ADDRESS" VARCHAR(512),
"CONTACTS_NAME" VARCHAR(255),
"CONTACTS_PHONE" VARCHAR(255),
"CONTACTS_LANDLINE_TELEPHONE" VARCHAR(255),
"REMARK" VARCHAR(512),
"CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"IS_DELETE" VARCHAR(2) DEFAULT '0' NOT NULL,
"X" VARCHAR(255),
"Y" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "CODE" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SCJGJ_NDWC"."T_GAS_STATION" IS '加油站表';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."ADDRESS" IS '加油站地址';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."BRAND" IS '加油站品牌';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."CODE" IS '加油站code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."CONTACTS_LANDLINE_TELEPHONE" IS '联系人固定电话';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."CONTACTS_NAME" IS '联系人姓名';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."CONTACTS_PHONE" IS '联系人手机号码';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."DISTRICT_CODE" IS '区code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."DISTRICT_NAME" IS '区name';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."ID" IS 'id';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."IS_DELETE" IS '是否删除';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."MANAGEMENT_NATURE" IS '经营性质';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."MANAGEMENT_STATE" IS '经营状态';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."NAME" IS '加油站名称';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."REMARK" IS '备注';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION"."UPDATE_TIME" IS '更新时间';


CREATE TABLE "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"
(
"ID" INT IDENTITY(2, 1) NOT NULL,
"DISTRICT_CODE" VARCHAR(255),
"DISTRICT_NAME" VARCHAR(255),
"GAS_STATION_NAME" VARCHAR(255),
"GAS_STATION_CODE" VARCHAR(255),
"EXAMINE_STATE" VARCHAR(2),
"EXAMINE_RESULT" VARCHAR(512),
"EXAMINE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(512),
"CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"IS_DELETE" VARCHAR(2) DEFAULT '0' NOT NULL,
"EXAMINE_DISPOSE" VARCHAR(512),
"GAS_APPARATUS_CODE" VARCHAR(255),
"GAS_GUN_CODE" VARCHAR(255),
"EXAMINE_NAME" VARCHAR(255),
"ENGINEER_NAME" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE" IS '加油站检查表';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."DISTRICT_CODE" IS '区code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."DISTRICT_NAME" IS '区name';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."ENGINEER_NAME" IS '工程师姓名';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."EXAMINE_DISPOSE" IS '检查后处理情况';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."EXAMINE_NAME" IS '检查人员名称';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."EXAMINE_RESULT" IS '检查结果';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."EXAMINE_STATE" IS '检查状况';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."EXAMINE_TIME" IS '检查时间';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."GAS_APPARATUS_CODE" IS '加油机的出厂编号';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."GAS_GUN_CODE" IS '加油枪自编号';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."GAS_STATION_CODE" IS '加油站code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."GAS_STATION_NAME" IS '加油站名称';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."ID" IS 'id';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."IS_DELETE" IS '是否删除';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."REMARK" IS '备注';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_EXAMINE"."UPDATE_TIME" IS '更新时间';


CREATE TABLE "SCJGJ_NDWC"."T_GAS_STATION_VOTE"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"DISTRICT_CODE" VARCHAR(255),
"DISTRICT_NAME" VARCHAR(255),
"VOTER_NAME" VARCHAR(255),
"VOTER_PHONE" VARCHAR(255),
"VOTER_ID_CARD" VARCHAR(255),
"VOTER_IP" VARCHAR(255),
"VOTE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
"GAS_STATION_NAME" VARCHAR(255),
"GAS_STATION_CODE" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"IS_DELETE" VARCHAR(2) DEFAULT '0' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SCJGJ_NDWC"."T_GAS_STATION_VOTE" IS '加油站投票表';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."DISTRICT_CODE" IS '区code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."DISTRICT_NAME" IS '区name';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."GAS_STATION_CODE" IS '加油站code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."GAS_STATION_NAME" IS '加油站名称';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."ID" IS 'id';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."IS_DELETE" IS '是否删除';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."VOTER_ID_CARD" IS '投票人身份证号码';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."VOTER_IP" IS '投票人ip';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."VOTER_NAME" IS '投票人姓名';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."VOTER_PHONE" IS '投票人手机号码';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_GAS_STATION_VOTE"."VOTE_TIME" IS '投票时间';


CREATE TABLE "SCJGJ_NDWC"."T_SYS_DEPT"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"CODE" VARCHAR(255),
"PID" INT,
"NAME" VARCHAR(255),
"NAME_SHORT" VARCHAR(255),
"INNER_CODE" VARCHAR(255),
"REMARK" VARCHAR(255),
"CAS_ID" INT,
"CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
"UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
"IS_DELETE" INT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."CAS_ID" IS 'casId';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."CODE" IS 'CODE';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."ID" IS 'id';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."INNER_CODE" IS '内部code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."IS_DELETE" IS '是否删除';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."NAME" IS '部门名称';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."NAME_SHORT" IS '简称';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."PID" IS '父id';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."REMARK" IS '备注';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DEPT"."UPDATE_TIME" IS '更新时间';


CREATE TABLE "SCJGJ_NDWC"."T_SYS_DICT"
(
"ID" INT IDENTITY(22, 1) NOT NULL,
"DICT_KEY" VARCHAR(255),
"DICT_VALUE" VARCHAR(255),
"DICT_GROUP" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
"IS_DELETE" VARCHAR(2) DEFAULT '0' NOT NULL,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SCJGJ_NDWC"."T_SYS_DICT" IS '字典表';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DICT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DICT"."DICT_GROUP" IS '组';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DICT"."DICT_KEY" IS '键';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DICT"."DICT_VALUE" IS '值';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DICT"."ID" IS 'id';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DICT"."IS_DELETE" IS '是否删除';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_DICT"."UPDATE_TIME" IS '更新时间';


CREATE TABLE "SCJGJ_NDWC"."T_SYS_MENU"
(
"ID" INT IDENTITY(156, 1) NOT NULL,
"CODE" VARCHAR(255) NOT NULL,
"P_CODE" INT,
"SUB_COUNT" INT DEFAULT 0,
"TYPE" INT,
"TITLE" VARCHAR(255),
"NAME" VARCHAR(255),
"COMPONENT" VARCHAR(255),
"MENU_SORT" INT,
"ICON" VARCHAR(255),
"PATH" VARCHAR(255),
"I_FRAME" NUMBER(1,0),
"CACHE" NUMBER(1,0) DEFAULT '0',
"HIDDEN" NUMBER(1,0) DEFAULT '0',
"PERMISSION" VARCHAR(255),
"CREATE_BY" VARCHAR(255),
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
"UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
"CAS_ID" VARCHAR(255),
"IS_DELETE" INT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "MENU_CODE" UNIQUE("CODE"),
CONSTRAINT "UNIQ_TITLE" UNIQUE("TITLE"),
CONSTRAINT "UNIQ_NAME" UNIQUE("NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SCJGJ_NDWC"."T_SYS_MENU" IS '系统菜单';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."CACHE" IS '缓存';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."CAS_ID" IS 'casId';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."CODE" IS 'code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."COMPONENT" IS '组件';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."HIDDEN" IS '隐藏';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."ICON" IS '图标';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."ID" IS 'ID';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."IS_DELETE" IS '是否删除';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."I_FRAME" IS '是否外链';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."MENU_SORT" IS '排序';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."NAME" IS '组件名称';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."PATH" IS '链接地址';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."PERMISSION" IS '权限';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."P_CODE" IS '上级菜单CODE';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."SUB_COUNT" IS '子菜单数目';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."TITLE" IS '菜单标题';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."TYPE" IS '菜单类型';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_MENU"."UPDATE_TIME" IS '更新时间';


CREATE  INDEX "INX_PID" ON "SCJGJ_NDWC"."T_SYS_MENU"("P_CODE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "SCJGJ_NDWC"."T_SYS_ROLE"
(
"ID" INT IDENTITY(7, 1) NOT NULL,
"CODE" VARCHAR(255) NOT NULL,
"NAME" VARCHAR(255) NOT NULL,
"LEVEL" INT,
"DESCRIPTION" VARCHAR(255),
"DATA_SCOPE" VARCHAR(255),
"CREATE_BY" VARCHAR(255),
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_TIME" TIMESTAMP(0),
"CAS_ID" VARCHAR(255),
"IS_DELETE" INT DEFAULT 0 NOT NULL,
NOT CLUSTER PRIMARY KEY("ID"),
UNIQUE("NAME"),
CONSTRAINT "ROLE_CODE" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SCJGJ_NDWC"."T_SYS_ROLE" IS '角色表';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."CAS_ID" IS 'casId';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."CODE" IS 'code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."DATA_SCOPE" IS '数据权限';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."ID" IS 'ID';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."IS_DELETE" IS '是否删除';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."LEVEL" IS '角色级别';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."NAME" IS '名称';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLE"."UPDATE_TIME" IS '更新时间';


CREATE  INDEX "ROLE_NAME_INDEX" ON "SCJGJ_NDWC"."T_SYS_ROLE"("NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "SCJGJ_NDWC"."T_SYS_ROLES_MENUS"
(
"MENU_CODE" BIGINT NOT NULL,
"ROLE_CODE" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("MENU_CODE", "ROLE_CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SCJGJ_NDWC"."T_SYS_ROLES_MENUS" IS '角色菜单关联';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLES_MENUS"."MENU_CODE" IS '菜单ID';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_ROLES_MENUS"."ROLE_CODE" IS '角色ID';


CREATE  INDEX "FKCNGG2QADOJHI3A651A5ADKVBQ" ON "SCJGJ_NDWC"."T_SYS_ROLES_MENUS"("ROLE_CODE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "SCJGJ_NDWC"."T_SYS_USER"
(
"ID" INT IDENTITY(49, 1) NOT NULL,
"CODE" VARCHAR(255) NOT NULL,
"DEPT_CODE" INT,
"USERNAME" VARCHAR(255),
"NICK_NAME" VARCHAR(255),
"GENDER" VARCHAR(2),
"PHONE" VARCHAR(255),
"EMAIL" VARCHAR(255),
"AVATAR_NAME" VARCHAR(255),
"AVATAR_PATH" VARCHAR(255),
"PASSWORD" VARCHAR(255),
"IS_ADMIN" INT DEFAULT 0,
"ENABLED" INT,
"CREATE_BY" VARCHAR(255),
"UPDATE_BY" VARCHAR(255),
"PWD_RESET_TIME" TIMESTAMP(0),
"CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
"UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
"CAS_ID" VARCHAR(255),
"ID_CARD" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "USER_CODE" UNIQUE("CODE"),
CONSTRAINT "UK_KPUBOS9GC2CVTKB0THKTKBKES" UNIQUE("EMAIL"),
CONSTRAINT "USERNAME" UNIQUE("USERNAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SCJGJ_NDWC"."T_SYS_USER" IS '系统用户';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."AVATAR_NAME" IS '头像地址';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."AVATAR_PATH" IS '头像真实路径';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."CAS_ID" IS 'casId';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."CODE" IS 'code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."DEPT_CODE" IS '部门code';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."ENABLED" IS '状态：1启用、0禁用';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."GENDER" IS '性别';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."ID" IS 'ID';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."ID_CARD" IS '身份证号';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."IS_ADMIN" IS '是否为admin账号';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."NICK_NAME" IS '昵称';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."PHONE" IS '手机号码';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."PWD_RESET_TIME" IS '修改密码的时间';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USER"."USERNAME" IS '用户名';


CREATE  INDEX "FK5RWMRYNY6JTHAAXKOGOWNKNQP" ON "SCJGJ_NDWC"."T_SYS_USER"("DEPT_CODE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "INX_ENABLED" ON "SCJGJ_NDWC"."T_SYS_USER"("ENABLED" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "FKPQ2DHYPK2QGT68NAUH2BY22JB" ON "SCJGJ_NDWC"."T_SYS_USER"("AVATAR_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "SCJGJ_NDWC"."T_SYS_USERS_ROLES"
(
"USER_CODE" BIGINT NOT NULL,
"ROLE_CODE" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("USER_CODE", "ROLE_CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SCJGJ_NDWC"."T_SYS_USERS_ROLES" IS '用户角色关联';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USERS_ROLES"."ROLE_CODE" IS '角色ID';
COMMENT ON COLUMN "SCJGJ_NDWC"."T_SYS_USERS_ROLES"."USER_CODE" IS '用户ID';


CREATE  INDEX "FKQ4EQ273L04BPU4EFJ0JD0JB98" ON "SCJGJ_NDWC"."T_SYS_USERS_ROLES"("ROLE_CODE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

